#' Plots slopes generated in fit_slope
#'
#' @param slope_df slopes data frame generated by fit_slope. includes a `method`
#' of estimation, `season` to group data by, `dataset` to group data by, and then
#' an `estimate` of the slope and an `lci` and `uci` for that estimate
#' @param data_sources vector of strings id-ing the data sources to be included,
#' need to match the sources in slope_df. Default is to not include ISD data as
#' they may be out of date.
#' @return A ggplot object
#' @export
plot_slopes <- function(
    slope_df,
    data_sources = c("NIS_2022", "NIS_2023")) {
  slope_df %>%
    mutate(
      dataset = factor(dataset,
        levels =
          c("NIS_2022", "NIS_2023")
      ),
      method = factor(method, levels = c("stan", "boot"))
    ) %>%
    dplyr::filter(dataset %in% data_sources) %>%
    ggplot(aes(dataset, estimate, color = season, lty = method)) +
    geom_point(position = position_dodge(0.25)) +
    geom_errorbar((aes(ymin = lci, ymax = uci)), position = position_dodge(0.25), width = 0.2) +
    cowplot::theme_cowplot() +
    theme(
      axis.title.x = element_blank(),
      legend.position = c(0.05, 0.35)
    ) +
    scale_y_continuous(
      limits = c(0, 3.5),
      expand = c(0, 0),
      breaks = seq(0, 3.5, by = 0.5)
    ) +
    labs(
      title = "Initial uptake rate, COVID-19 booster",
      y = "Rate (p.p. per week)"
    )
}
